spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/user_login
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev

access-token :
  private : ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
  public : ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
refresh-token :
  private : ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
  public : ${REFRESH_TOKEN_PUBLIC_KEY_PATH}
logging :
  level :
    org.springframework.security : DEBUG


